<?php $this->headMeta()->appendName('description', 'Все об играх вселенной Звездных Войн собранных в одном месте.'); ?>
<?php $this->headTitle('Force-Leads: Games'); ?>

<div class="container game_wrap">
<ul>
    <?php foreach($this->games as $value): ?>
    <?php $value['status'] == 1 ? $status = '/games/id/' . $value['id'] : $status = ''; ?>
    <li class="">
        <div class="game_block col-xs-12">
            <div class="col-xs-12">
                <div class="game_poster" title="<?php echo $value['title']; ?>">
                    <?php $size = getimagesize ('http://' . $_SERVER['HTTP_HOST'] . '/img/games/' . $value['id'] . '/' . $value['poster']); ?>
                    <img width="<?php echo $size[0] ?>" height="<?php echo $size[1] ?>" class="img-responsive" src="/img/games/<?php echo $value['id']; ?>/<?php echo $value['poster']; ?>" alt="pic" />
                </div>
                <div class="game_title"><a href="<?php echo $status; ?>"><?php echo $value['title']; ?></a></div>
            </div>
        </div>
    </li>
    <?php endforeach; ?>
</ul>
</div>