
<div class="gamesWrap">
    <?php foreach($this->games as $value): ?>

        <div class="oneWrap">
            <div class="gameBlock" title="<?php echo $value['title']; ?>">
                <img src="/img/games/<?php echo $value['id']; ?>/<?php echo $value['poster']; ?>" alt="pic" />
                <div class="descBlock"><a href="#"><?php echo $value['title']; ?></a></div>
            </div>

        </div>

    <?php endforeach; ?>
</div>