<?php
$identity = Zend_Auth::getInstance()->getStorage()->read();
?>

<div class="mediaWrap">
    <div class="episodeWrap">
        <div class="poster">
            <a href="#"></a>
        </div>
    </div>
    <div class="episodeWrap">
        <div class="poster"></div>
    </div>
    <div class="episodeWrap">
        <div class="poster"></div>
    </div>
    <div class="episodeWrap">
        <div class="poster"></div>
    </div>
    <div class="episodeWrap">
        <div class="poster"></div>
    </div>
    <div class="episodeWrap">
        <div class="poster"></div>
    </div>
    <div class="episodeWrap">
        <div class="poster"></div>
    </div>
</div>

<?php echo $this->pagination(); ?>
