<div class="contentWrapperArticle">

    <div class="contentLeftPart">
        <img src="/img/article/<?php echo $this->articles['id']; ?>/<?php echo $this->articles['miniImg']; ?>" class="miniImg"  alt="miniImg" />

        <div class="author">
            <p><?php echo $this->articles['addDate']; ?></p>
        </div>
    </div>

    <div class="contentRightPart">
        <div class="contentText">
            <h2><?php echo $this->articles['title']; ?></h2>
            <?php echo $this->articles['full']; ?>
        </div>
    </div>

</div>

