<?php $this->doctype('XHTML1_RDFA'); ?>

<?php $this->headMeta()->setProperty('og:type', 'article'); ?>
<?php $this->headMeta()->setProperty('og:site_name', 'force-leads.com'); ?>
<?php $this->headMeta()->setProperty('og:title', $this->articles['title']); ?>
<?php $this->headMeta()->setProperty('og:url', $this->url()); ?>
<?php $this->headMeta()->setProperty('og:description', $this->articles['shortDesc']); ?>
<?php $this->headMeta()->setProperty('og:image', 'http://force-leads.com/img/article/' . $this->articles['id'] . '/' . $this->articles['miniImg']); ?>
<?php $this->headMeta()->appendName('description', $this->articles['shortDesc']); ?>
<?php $this->headMeta()->appendName('title', $this->articles['title']); ?>
<?php $this->headLink()->headLink(array('rel' => 'image_src', 'href' => 'http://force-leads.com/img/article/' . $this->articles['id'] . '/' . $this->articles['miniImg'])); ?>
<?php $this->headScript()->appendFile('/js/vk.comments.js', $type = 'text/javascript', $attrs = array('' => 'async'));?>
<?php $this->headScript()->appendFile('/js/social.js', $type = 'text/javascript', $attrs = array('' => 'async'));?>

<div itemscope itemtype="http://schema.org/Article" class="col-xs-12 col-sm-12 col-md-12 col-lg-12 block">
    <div class="article_block">
        <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3 left_part">
            <div class="pic_wrap">
                <?php $size = getimagesize ('http://' . $_SERVER['HTTP_HOST'] . '/img/article/' . $this->articles['id'] . '/' . $this->articles['miniImg']); ?>
                <img width="<?php echo $size[0] ?>" itemprop="image" class="img_pic" src="/img/article/<?php echo $this->articles['id']; ?>/<?php echo $this->articles['miniImg']; ?>" alt="<?php echo $this->articles['miniImg']; ?>" />
            </div>
            <div class="col-xs-12 time">
                <time itemprop="datePublished" content="<?php echo $this->articles['addDate']; ?>"  datetime="<?php echo $this->articles['addDate']; ?>"><?php echo $this->articles['addDate']; ?></time>
            </div>
            <div class="col-xs-12 social">
                <a onclick="share.vkontakte(<?php echo "'" . $this->url() . "'"; ?>, <?php echo "'" . $this->articles['title'] . "'"; ?>, <?php echo "'http://force-leads.com/img/article/" . $this->articles['id'] . "/" . $this->articles['miniImg'] . "'"; ?>, <?php echo "'" . $this->articles['shortDesc'] . "'"; ?>)"><div class="social_vk" title="VKontakte"></div></a>
                <a onclick="share.facebook(<?php echo "'" . $this->url() . "'"; ?>, <?php echo "'" . $this->articles['title'] . "'"; ?>, <?php echo "'http://force-leads.com/img/article/" . $this->articles['id'] . "/" . $this->articles['miniImg'] . "'"; ?>, <?php echo "'" . $this->articles['shortDesc'] . "'"; ?>)"><div class="social_fb" title="Facebook"></div></a>
                <a onclick="share.twitter(<?php echo "'" . $this->url() . "'"; ?>, <?php echo "'" . $this->articles['title'] . "'"; ?>)"><div class="social_tweet" title="Twitter"></div></a>
                <a onclick="share.googleplus(<?php echo "'" . $this->url() . "'"; ?>)"><div class="social_google_plus" title="Google+"></div></a>
            </div>
        </div>

        <div class="col-xs-12 col-sm-9 col-md-9 col-lg-9 right_part">
            <h2 itemprop="name"><?php echo strip_tags($this->headTitle($this->articles['title'])); ?></h2>
            <article itemprop="articleBody"><?php echo $this->articles['full']; ?></article>
        </div>
    </div>
    <div class="comments_block">
        <script type="text/javascript">
            VK.init({apiId: 4018526, onlyWidgets: true});
        </script>

        <div id="vk_comments"></div>

        <script type="text/javascript">
            if (screen.width < 1024) var par = "260";
            else if (screen.width > 1024) var par = "480";
            VK.Widgets.Comments("vk_comments", {limit: 5, width: par, attach: "*"});
        </script>
    </div>
</div>