<ul class="list">

    <?php foreach ($this->articles as $value): ?>

    <li id="contentWrapper<?php echo $value['id']; ?>">
        <div class="contentWrapper">
            <a class="superLink" href="/article/id/<?php echo $value['id']; ?>" name="<?php echo $value['id']; ?>"></a>

            <div class="contentLeftPart">
                <img src="/img/article/<?php echo $value['id']; ?>/<?php echo $value['miniImg']; ?>" class="miniImg"  alt="miniImg" />

                <div class="author">
                    <p><?php echo $value['addDate']; ?></p>
                </div>
            </div>

            <div class="contentRightPart">
                <div class="contentText">
                    <h2><?php echo $value['title']; ?></h2>
                    <p><?php echo $value['shortDesc']; ?></p>
                </div>
            </div>
        </div>
    </li>

    <?php endforeach ?>
</ul>

<?php echo $this->pagination(); ?>


<!--
echo $this->form;

div#test>ul.some>li*5>lorem
-->