<?php $this->headMeta()->appendName('description', 'Архив вселенной Звездных Войн, новости собраные в одном месте.'); ?>
<?php $this->headTitle('Force-Leads'); ?>

<div class="container content_center">
    <ul class="list-unstyled">

        <?php foreach ($this->articles as $value): ?>

        <li id="contentWrapper<?php echo $value['id']; ?>">
            <div itemscope itemtype="http://schema.org/Article" class="col-xs-12 col-sm-12 col-md-12 col-lg-12 block">
                <a itemprop="url" class="block_link" href="/article/id/<?php echo $value['id']; ?>" name="<?php echo $value['id']; ?>"></a>

                <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3 left_part">
                    <div class="pic_wrap">
                        <?php //$size = getimagesize ('http://' . $_SERVER['HTTP_HOST'] . '/img/article/' . $value['id'] . '/' . $value['miniImg']); ?>
                        <img width="<?php /*echo $size[0] */?>" height="<?php /*echo $size[1] */?>" itemprop="image" class="img_pic img-responsive" src="/img/article/<?php echo $value['id']; ?>/<?php echo $value['miniImg']; ?>" title="<?php echo $value['title']; ?>" alt="<?php echo $value['miniImg']; ?>" />
                    </div>
                    <div class="col-xs-12 time">
                        <time datetime="<?php echo $value['addDate']; ?>"><?php echo $value['addDate']; ?></time>
                    </div>
                </div>

                <div class="col-xs-12 col-sm-9 col-md-9 col-lg-9 right_part">
                    <h2 itemprop="name"><?php echo $value['title']; ?></h2>
                    <span itemprop="description"><?php echo $value['shortDesc']; ?></span>
                </div>
            </div>
        </li>

        <?php endforeach ?>

    </ul>
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 pagination"><?php echo $this->pagination(); ?></div>
</div>
