<div class="movieWrap">

    <div class="movieBlock">
        <h2><?php echo strip_tags($this->headTitle($this->movie['title'])); ?></h2>
    </div>

    <div class="movieBlock">
        <div class="part1">
            <div class="movieShort"><?php echo $this->movie['short']; ?></div>
            <div class="movieActor"><?php echo $this->movie['actors']; ?></div>
        </div>

        <div class="part2">
            <div class="moviePic">
                <div id="content">
                    <div id="slider">
                        <ul>
                            <?php foreach ($this->movieImg as $key => $value):

                                if ($key == 'slider'):

                                    foreach($value as $subVal): ?>

                                        <li><img src="/img/movie/<?=$subVal['movie_id']?>/<?=$subVal['addImg']?>" /></li>

                                    <?php endforeach;
                                endif;
                            endforeach; ?>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="movieBlock">
        <div class="part3">
            <div class="movieDesc">
                <?php echo $this->movie['full']; ?>
            </div>
            <div class="movieFunny"><?php echo $this->movie['funny']; ?></div>
        </div>
    </div>

    <div class="movieBlock">
        <div class="part4">
            <div class="movieOst"><?php echo $this->movie['ostList']; ?></div>
        </div>
        <div class="part5">
            <div class="movieOstPic">
                <?php foreach ($this->movieImg as $key => $value):

                    if ($key == 'ost'):

                        foreach($value as $subVal): ?>

                            <img src="/img/movie/<?=$subVal['movie_id']?>/<?=$subVal['addImg']?>" />

                        <?php endforeach;
                    endif;
                endforeach; ?>
            </div>
        </div>
    </div>
</div>