<?php $this->headMeta()->appendName('description', 'Все об фильмах вселенной Звездных Войн.'); ?>
<?php $this->headTitle('Force-Leads: Movie'); ?>

<div class="container movie_wrap">

    <?php foreach ($this->receive as $value): ?>
    <?php $value['status'] == 1 ? $status = '/movie/id/' . $value['id'] : $status = ''; ?>

    <div class="episode_wrap col-xs-12 col-sm-6 col-md-4 col-lg-4">
        <div class="col-xs-12">
            <div class="episode_poster" title="<?php echo $value['title']; ?>">
                <a class="block_link" href="<?php echo $status; ?>"></a>
                <?php //$size = getimagesize ('http://' . $_SERVER['HTTP_HOST'] . '/img/movie/' . $value['id'] . '/' . $value['miniImg']); ?>
                <img width="<?php /*echo $size[0] */?>" height="<?php /*echo $size[1] */?>" class="img-responsive" src="/img/movie/<?php echo $value['id']; ?>/<?php echo $value['miniImg']; ?>" alt="<?php echo $value['title']; ?>" />
            </div>
        </div>
    </div>

    <?php endforeach; ?>

</div>