<div class="mediaWrap">

<?php
$identity = Zend_Auth::getInstance()->getStorage()->read();

foreach ($this->receive as $value):

?>

   <div class="episodeWrap">
        <div class="poster" title="<?php echo $value['title']; ?>">
            <a href="/movie/id/<?php echo $value['id']; ?>"></a>
            <img src="/img/movie/<?php echo $value['id']; ?>/<?php echo $value['miniImg']; ?>" alt="<?php echo $value['title']; ?>" />
        </div>
    </div>

<?php endforeach; ?>
</div>


