<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Архив вселенной Звездных Войн, новости собраные в одном месте.">
    <meta name="author" content="Siada-Apius">
    <link rel="shortcut icon" href="http://www.force-leads.com/favicon.png">
    <link href='http://fonts.googleapis.com/css?family=Comfortaa' rel='stylesheet' type='text/css'>


    <?php /*$this->headLink()->appendStylesheet('/css/bootstrap.css'); */?><!--
    --><?php /*$this->headLink()->appendStylesheet('/css/bootstrap-responsive.css'); */?>
   <!-- <?php /*$this->headLink()->appendStylesheet('/css/custom.css');*/?>

    --><?php /*$this->headScript()->appendFile('/js/bootstrap.js');*/?>
    <?php /*$this->headScript()->appendFile('/js/jquery/jquery-1.8.1.js');*/?><!--
    <?php /*$this->headScript()->appendFile('/js/jquery/jquery.js');*/?>

    <!--SLIDER - START-->
    <?php /*$this->headLink()->appendStylesheet('/slider/css/screen.css');*/?>
    <?php /*$this->headScript()->appendFile('/slider/js/easySlider1.7.js');*/?>
    <!--SLIDER - END --->

    <!-- WYSIWYG - START -->
    <?php /*$this->headLink()->appendStylesheet('/wysiwyg/markitup/skins/simple/style.css');*/?>
    <?php /*$this->headLink()->appendStylesheet('/wysiwyg/markitup/sets/default/style.css');*/?>
    <?php /*$this->headScript()->appendFile('/wysiwyg/markitup/jquery.markitup.js');*/?>
    <?php /*$this->headScript()->appendFile('/wysiwyg/markitup/sets/default/set.js');*/?>
    <!-- WYSIWYG - END ---->



    <!-- Custom styles for this template -->
    <link href="../../../www/bootstrap/3.0.0/examples/sticky-footer/sticky-footer.css" rel="stylesheet">

    <!--NEW STYLE-->
    <?php $this->headLink()->appendStylesheet('/bootstrap/3.0.0/dist/css/bootstrap.css');?>
    <?php $this->headLink()->appendStylesheet('/css/manual.css');?>
    <!--[if lt IE 9]>
    <script src="/bootstrap/3.0.0/assets/js/html5shiv.js"></script>
    <script src="/bootstrap/3.0.0/assets/js/respond.min.js"></script>
    <![endif]-->




    <?php echo $this->jQuery(); ?>
    <?php echo $this->headLink();?>
    <?php echo $this->headScript();?>

    <title>Force-Leads</title>

</head>

<body>
<div id="wrap">
    <div class="row">
        <div class="modal-header"></div>

        <div class="navbar navbar-default bar">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <?php
                $identity = Zend_Auth::getInstance()->getStorage()->read();

                if (isset($identity->role)  && $identity->role == 'admin'){
                    echo $this  ->navigation()
                        ->menu()
                        ->setMaxDepth(2)
                        ->setUlClass('nav navbar-nav')
                        ->render(new My_Navigation($this->navigation()->findAllBy('tag','admin',true)))
                    ;

                } else {
                    echo $this  ->navigation()
                        ->menu()
                        ->setMaxDepth(2)
                        ->setUlClass('nav navbar-nav')
                        ->render(new My_Navigation($this->navigation()->findAllBy('tag','topMenu',true)))
                    ;
                }

                ?>
                <form class="navbar-form navbar-right" role="search" method="get" action="/search">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search">
                    </div>
                </form>
            </div><!--/.navbar-collapse -->
        </div>
    </div>

    <div class="row content">
        <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3"></div>
        <div class="col-xs-12 col-sm-9 col-md-7 col-lg-6"><?php echo $this->layout()->content; ?></div>
        <div class="col-xs-12 col-sm-12 col-md-2 col-lg-3"></div>
    </div>
</div>

<div id="footer">
    <span>Developed for distribution STAR WARS</span>

    <!--LiveInternet counter-->
    <div class="counter">
        <script type="text/javascript">
            document.write("" +
                "<a href='http://www.liveinternet.ru/click' target=_blank>" +
                "<img src='//counter.yadro.ru/hit?t19.2;r" + escape(document.referrer) +
                ((typeof(screen)=="undefined")?"":";s"+screen.width+"*"+screen.height+"*"+(screen.colorDepth?screen.colorDepth:screen.pixelDepth))
                + ";u" + escape(document.URL) + ";" + Math.random() + "' border=0 width=88 height=31 alt='' title='LiveInternet: показано число просмотров за 24 часа, посетителей за 24 часа и за сегодня'><\/a>")
        </script>
    </div>
    <!--/LiveInternet-->
</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="/bootstrap/3.0.0/assets/js/jquery.js"></script>
<script src="/bootstrap/3.0.0/dist/js/bootstrap.min.js"></script>

<!--Google analytics-->
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-44093366-1', 'force-leads.com');
    ga('send', 'pageview');

</script>

</body>
</html>