<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="author" content="Siada-Apius">
<?php echo $this->headMeta();?>
<link rel="shortcut icon" href="http://www.force-leads.com/favicon.png">

<?php $this->headLink()->appendStylesheet('/bootstrap/3.0.0/dist/css/bootstrap.min.css');?>
<?php $this->headLink()->appendStylesheet('/css/manual.css');?>

<?php echo $this->headLink();?>
<?php echo $this->headTitle();?>


</head>

<body>
<div id="wrap">
    <div class="row">
        <header>
        <div class="modal-header">
            <div class="hidden-xs hidden-sm col-md-3 col-lg-3"></div>
            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 logo">
                <a href="http://force-leads.com">
                    <img alt="logo picture" src="http://force-leads.com/img/style/logo2.png"/>
                </a>
            </div>
            <div class="hidden-xs hidden-sm col-md-3 col-lg-3"></div>
        </div>

        <nav>
        <div class="navbar navbar-default bar">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <?php $identity = Zend_Auth::getInstance()->getStorage()->read();

                if (isset($identity->role)  && $identity->role == 'admin'){
                    echo $this  ->navigation()
                                ->menu()
                                ->setMaxDepth(2)
                                ->setUlClass('nav navbar-nav')
                                ->render(new My_Navigation($this->navigation()->findAllBy('tag','admin',true)))
                    ;

                } else {
                    echo $this  ->navigation()
                                ->menu()
                                ->setMaxDepth(2)
                                ->setUlClass('nav navbar-nav')
                                ->render(new My_Navigation($this->navigation()->findAllBy('tag','topMenu',true)))
                    ;
                }
                ?>

                <form class="navbar-form navbar-right" role="search" method="get" action="/search">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search"name="query" />
                    </div>
                </form>
            </div><!--/.navbar-collapse -->
        </div>
        </nav>
        </header>
    </div>

    <div class="row content">
        <aside>
        <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3"></div></aside>
        <section><div class="col-xs-12 col-sm-9 col-md-7 col-lg-6"><?php echo $this->layout()->content; ?></div></section>
        <aside><div class="col-xs-12 col-sm-12 col-md-2 col-lg-3"></div></aside>
    </div>
</div>

<footer>
<div id="footer">

    <div><span>Developed for distribution STAR WARS</span></div>

    <!--LiveInternet counter-->
    <div class="counter">
        <script type="text/javascript">
            document.write(""+"<a href='http://www.liveinternet.ru/click' target=_blank>"+"<img src='//counter.yadro.ru/hit?t19.2;r" + escape(document.referrer)+((typeof(screen)=="undefined")?"":";s"+screen.width+"*"+screen.height+"*"+(screen.colorDepth?screen.colorDepth:screen.pixelDepth))+ ";u" + escape(document.URL) + ";" + Math.random() + "' border=0 width=88 height=31 alt='' title='LiveInternet: показано число просмотров за 24 часа, посетителей за 24 часа и за сегодня'><\/a>")
        </script>
    </div>
    <!--/LiveInternet-->

</div>
</footer>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->

<!--[if lt IE 9]>
<script src="/bootstrap/3.0.0/assets/js/html5shiv.js"></script>
<script src="/bootstrap/3.0.0/assets/js/respond.min.js"></script>
<![endif]-->
<script src="/bootstrap/3.0.0/assets/js/jquery.js"></script>
<script src="/bootstrap/3.0.0/dist/js/bootstrap.min.js"></script>
<script src="/wysiwyg/markitup/jquery.markitup.js"></script>
<script src="/wysiwyg/markitup/sets/default/set.js"></script>
<script src="/js/manual.js"></script>

<!--Google analytics-->
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-44093366-1', 'force-leads.com');
    ga('send', 'pageview');
</script>
</body>
</html>