<html>
<head>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>S&M</title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <?php $this->headLink()->appendStylesheet('/css/bootstrap.css'); ?>
    <?php $this->headLink()->appendStylesheet('/css/bootstrap-responsive.css'); ?>
    <?php $this->headLink()->appendStylesheet('/css/custom.css');?>

    <?php   $this->headScript()->appendFile('/js/bootstrap.js');?>
    <?php   $this->headScript()->appendFile('/js/jquery/jquery.js');?>

    <?php echo $this->jQuery(); ?>
    <?php echo $this->headLink();?>
    <?php echo $this->headScript();?>

</head>

    <body>
        <div class="wrapper">

            <div class="headerBig">

                <div class="headerLeft"></div>

                <div class="headerRight">

                     <div class="headerInfo">
                         <h3>The force is strong in you, Skywalker</h3>
                     </div>

                    <div class="headerNav">
                        <div class="navbar">
                            <div class="navbar-inner">
                                <?php
                                $identity = Zend_Auth::getInstance()->getStorage()->read();

                                if (isset($identity->role)  && $identity->role == 'admin'){
                                    echo $this  ->navigation()
                                        ->menu()
                                        ->setMaxDepth(2)
                                        ->setUlClass('nav')
                                        ->render(new My_Navigation($this->navigation()->findAllBy('tag','admin',true)))
                                    ;
                                }

                                else {
                                    echo $this  ->navigation()
                                        ->menu()
                                        ->setMaxDepth(2)
                                        ->setUlClass('nav')
                                        ->render(new My_Navigation($this->navigation()->findAllBy('tag','topMenu',true)))
                                    ;
                                }

                                ?>
                            </div>
                        </div>
                    </div>

                </div>



                <!--<div class="headerRight">
                    <?php
/*                    if (isset($identity)){
                        echo '
                            <table>
                                <tr>
                                    <td>Nickname <==> </td>
                                    <td>'. $identity->nickname .'</td>
                                </tr>
                                <tr>
                                    <td>Email <==> </td>
                                    <td>'. $identity->email .'</td>
                                </tr>
                                <tr>
                                    <td>Created Time <==> </td>
                                    <td>'. $identity->created .'</td>
                                </tr>
                                <tr>
                                    <td>Status <==> </td>
                                    <td>'. $identity->role .'</td>
                                </tr>
                            </table>
                        ';
                    }
                    */?>
                </div>-->

            </div>


            <div class="content">

                <div class="contentLeft">
                    <?php
                    $identity = Zend_Auth::getInstance()->getStorage()->read();

                    if (isset($identity->role)  && $identity->role == 'admin'): ?>

                        <div class="adminMenu">
                            <ul>
                                <li><a class="regLink" href="/admin/add/">Add new articles (This Menu see only ADMIN)</a></li>
                                <li><a class="regLink" href="/admin/comments/">Work with comments (This Menu see only ADMIN)</a></li>
                            </ul>
                        </div>

                        <?php else :?>
                        left menu
                        <?php endif ?>
                </div>

                <div class="contentMiddle">
                    <?php echo $this->title; ?>
                    <?php echo $this->layout()->content; ?>

                </div>

                <div class="contentRight">
                    <?php if($this->sukaID) $this->comments($this->sukaID);?>
                    <?php #$this->comments($this->sukaID);?>
                </div>

            </div>


            <div class="footer">
                <a href="/index/mail/">check mail</a>

            </div>

        </div>
    </body>
</html>