<?php $identity = Zend_Auth::getInstance()->getStorage()->read();?>
<?php if(isset($identity->role) && $identity->role == "admin"): ?>

    <h1>An error occurred</h1>
    <h2><?php echo $this->message ?></h2>

    <?php if (isset($this->exception)): ?>

        <h3>Exception information:</h3>
        <p>
            <b>Message:</b> <?php echo $this->exception->getMessage() ?>
        </p>

        <h3>Stack trace:</h3>
        <pre><?php echo $this->exception->getTraceAsString() ?></pre>

        <h3>Request Parameters:</h3>
        <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?></pre>
    <?php endif ?>

<?php else: ?>

    <div class="col-md-12 page404">
        <div class="well alert-warning">
            <h2><?php echo $this->title = "404 NOT FOUND";?></h2>
            <p>Сторінки яку Ви шукаєте не існує, або Вам необхідно авторизуватися для її перегляду.</p>
            <p>Пропонуємо повернутися вам на <a href = "<?php echo 'http://' . $_SERVER['HTTP_HOST']; ?>">Головну сторінку</a> або написати нам через форму зворотнього звязку</p>
        </div>
    </div>

<?php endif ?>