<div class="searchWrap">

    <?php foreach ( $this->total as $key => $value ): ?>

        <?php

            switch($key){

                case 'movies':      $link = "/movie/id/";       break;
                case 'articles':    $link = "/article/id/";     break;
                case 'games':       $link = "/games/id";        break;

            }

        ?>

        <?php foreach ($value as $subVal):?>

            <div class="well">
                <a href="<?=$link . $subVal['id']; ?>"><?=$subVal['title']; ?></a>
            </div>

        <?php endforeach;?>

    <?php endforeach; ?>

</div>

