<div class="well">
    <table class="table table-hover" border=1px>
        <tr>
            <td></td>
            <td>You have indexed</td>
        </tr>
        <tr>
            <td>Movies</td>
            <td><?php echo count($this->total['movie']); ?></td>
        </tr>
        <tr>
            <td>Articles</td>
            <td><?php echo count($this->total['article']) ; ?></td>
        </tr>
        <tr>
            <td>Games</td>
            <td>//TODO<?php #echo count($this->total['game']); ?></td>
        </tr>
        <tr>
            <td>TOTAL </td>
            <td>
                <?php echo count($this->total['movie']) + count($this->total['article']) /*+ count($this->total['game'])*/; ?>
            </td>
        </tr>
    </table>
</div>