<!--
<form class="form-horizontal" method="POST">

    <div class="control-group">
        <input type="text" id="username" placeholder="Login" name="login">
    </div>

    <div class="control-group">
        <input type="password" id="password" placeholder="Password" name="password">
    </div>

    <div class="control-group">
        <button type="submit" class="btn btn-success" id="sign">Log in</button>
    </div>

</form>
-->



<div class="loginForm error">
<?php
    echo $this->form;
?>
    <div class="regLink">
        <a href="registration">Join to the dark side</a>
    </div>
</div>


