<!--
<form class="form-horizontal" id = "regForm">

    <div class="control-group">
        <div class="input_reg">
            <input type="text" id="nickname" placeholder="Nickname">
        </div>
    </div>

    <div class="control-group">
        <div class="input_reg">
            <input type="text" id="email" placeholder="Email">
        </div>
    </div>

    <div class="control-group">
        <div class="input_reg">
            <input type="password" id="password" placeholder="Password">
        </div>
    </div>

    <div class="control-group">
        <div class="input_reg">
            <input type="password" id="confirm" placeholder="Password again">
        </div>
    </div>

    <div class="control-group">
        <button type="submit" class="btn btn-success" id="reg">Sign in</button>
    </div>

</form>
-->
<div class="loginForm error">
<?php
    echo $this->form;
?>

<div class="regLink">
    <a href="/user/login">Go back to the Login form</a>
</div></div>