<?php $this->headLink()->appendStylesheet('/wysiwyg/markitup/skins/simple/style.css');?>
<?php $this->headLink()->appendStylesheet('/wysiwyg/markitup/sets/default/style.css');?>

<div class="well">
<?php

    if ($this->form) {

        echo '<p>Add New Article Form</p>';
        echo '<form id="addForm" method="post" enctype="multipart/form-data" name="addForm">';
        echo $this->form->title;
        echo $this->form->shortDesc;
        echo '<div id="textareaFeedback"></div>';
        echo $this->form->full;
        echo $this->form->author;
        echo $this->form->addDate;
        echo $this->form->updateDate;
        echo $this->form->miniImg;
        echo $this->form->imgInText;
        echo $this->form->status;
        echo $this->form->submit;
        echo '</form>';

    } else if ($this->movie) {
        echo '<p>Add New Movie Form</p>';
        echo $this->movie;

    } else if ($this->gameForm) {
        echo '<p>Add New Game Form</p>';
        echo $this->gameForm;
    }

?>
</div>
