<?php if ($this->form): ?>

    <form enctype="multipart/form-data" method = "POST">
        <div class="contEdit">

            <div class="leftPartArticle">

                <img class="articleMini" src="/img/article/<?php echo $this->articles['id']; ?>/<?php echo $this->articles['miniImg']; ?>" alt="miniImg" />

                <?php echo $this->form->getElement('miniImg'); ?>
                <?php echo $this->form->getElement('imgInText'); ?>

                <div class="authorEdit">
                    <?php echo $this->form->getElement('id'); ?>
                    <?php echo $this->form->getElement('author'); ?>
                    <?php echo $this->form->getElement('updateDate'); ?>
                </div>

                <?php echo $this->form->getElement('submit'); ?> <!-- SUBMIT -->

            </div>

            <div class="rightPartArticle">

                <div class="textContentEdit">

                    <?php echo $this->form->getElement('title'); ?>
                    <?php echo $this->form->getElement('shortDesc'); ?>
                    <?php echo $this->form->getElement('full'); ?>

                </div>

            </div>
        </div>
    </form>


<?php elseif ($this->formMovie): ?>

    <div class="movieWrap">

        <form enctype="multipart/form-data" method="POST">

            <div class="movieBlock admin">
                <h2><?php echo $this->formMovie->getElement('title'); ?></h2>
            </div>

            <div class="movieBlock admin">

                <div class="part1">
                    <div class="movieShort"><?php echo $this->formMovie->getElement('short'); ?></div>
                    <div class="movieActor"><?php echo $this->formMovie->getElement('actors'); ?></div>
                </div>

                <div class="part2">
                    <div class="moviePic">

                        <img src="/img/movie/<?php echo $this->movie['id']; ?>/<?php echo $this->movie['miniImg']; ?>" />

                        <?php echo $this->formMovie->getElement('miniImg'); ?>
                    </div>
                    <div class="movieSlider">
                        <?php echo $this->formMovie->getElement('addImg'); ?>
                        <?php echo $this->formMovie->getElement('ostImg'); ?>
                        <?php echo $this->formMovie->getElement('textImg'); ?>
                    </div>
                </div>
            </div>

            <div class="movieBlock admin">

                <div class="part3">
                    <div class="movieDesc"><?php echo $this->formMovie->getElement('full'); ?></div>
                    <div class="movieFunny"><?php echo $this->formMovie->getElement('funny'); ?></div>
                </div>
            </div>

            <div class="movieBlock admin">

                <div class="part4">
                    <div class="movieOst"><?php echo $this->formMovie->getElement('ostList'); ?></div>
                </div>

            </div>

            <?php echo $this->formMovie->getElement('id'); ?>

            <div class="save_button"><?php echo $this->formMovie->getElement('submit'); ?></div>
        </form>

        <div class="movieBlock admin">
            <h4>SLIDER PICTURES</h4>
            <?php foreach ($this->movieImg as $key => $value):

                if ($key == 'slider'):

                    foreach($value as $subVal): ?>

                        <div class="episodeWrapEdit deletePic">

                            <div class="delete_cross">
                                <input class='movieDeleteInput' type='image' src='/img/style/remove_close_button_x_delete.png' value='<?php echo $subVal['id'] ?>' title='<?php echo $subVal['id'] ?>'>
                            </div>

                            <div class="poster">
                                <img src="/img/movie/<?=$subVal['movie_id']?>/<?=$subVal['addImg']?>" class="posterImg"/>
                            </div>
                        </div>

                    <?php endforeach;
                endif;
            endforeach; ?>
        </div>

        <div class="movieBlock admin">
            <h4>OST PICTURES</h4>

            <?php foreach ($this->movieImg as $key => $value):

                if ($key == 'ost'):

                    foreach($value as $subVal): ?>

                        <div class="movieOstPicAdmin deletePic">

                            <div class="delete_cross">
                                <input class='movieDeleteInput' type='image' src='/img/style/remove_close_button_x_delete.png' value='<?php echo $subVal['id'] ?>' title='<?php echo $subVal['id'] ?>'>
                            </div>

                            <img src="/img/movie/<?=$subVal['movie_id'];?>/<?=$subVal['addImg'];?>" />
                        </div>

                    <?php
                    endforeach;
                endif;
            endforeach; ?>
        </div>

        <div class="movieBlock admin">
            <h4>TEXT PICTURES</h4>

            <?php foreach ($this->movieImg as $key => $value):

                if ($key == 'text'):

                    foreach($value as $subVal): ?>

                        <div class="movieOstPicAdmin deletePic">

                            <div class="delete_cross">
                                <input class='movieDeleteInput' type='image' src='/img/style/remove_close_button_x_delete.png' value='<?php echo $subVal['id'] ?>' title='<?php echo $subVal['id'] ?>'>
                            </div>

                            <img src="/img/movie/<?=$subVal['movie_id'];?>/<?=$subVal['addImg'];?>" />
                        </div>

                    <?php
                    endforeach;
                endif;
            endforeach; ?>
        </div>

    </div>
<?php endif; ?>


