
<div class="gamesWrap">
<?php foreach($this->games as $value): ?>

    <div class="oneWrap">
        <div class="gameBlock" title="<?php echo $value['title']; ?>">

            <img src="/img/games/<?php echo $value['id']; ?>/<?php echo $value['poster']; ?>" alt="pic" />
            <div class="descBlock">
                <a href="/admin/games/edit/id/<?php echo $value['id']; ?>">Edit</a>
                <span>&#124;</span>
                <a class="deleteGame"><input type="hidden" value="<?php echo $value['id']; ?>">Delete</a>
            </div>
        </div>
    </div>

<?php endforeach; ?>
</div>