<div class="container content_center">
    <ul class="list-unstyled">

        <?php foreach ($this->articles as $value): ?>

        <li>
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 block">

                <div class="delete_cross">
                    <input data-param="article" class='delete_article' type='image' src='/img/style/remove_close_button_x_delete.png' value='<?php echo $value['id'] ?>' title='<?php echo $value['id'] ?>'>
                </div>

                <a class="block_link" href="/admin/article/edit/id/<?php echo $value['id']; ?>" name="<?php echo $value['id']; ?>"></a>

                <div class="col-xs-11 col-sm-3 col-md-3 col-lg-3 left_part">
                    <div class="pic_wrap">
                        <img class="img_pic img-responsive" src="/img/article/<?php echo $value['id']; ?>/<?php echo $value['miniImg']; ?>" title="<?php echo $value['title']; ?>" alt="<?php echo $value['miniImg']; ?>" />
                    </div>
                    <div class="col-xs-12 time">
                        <?php echo $value['updateDate']; ?>
                    </div>
                </div>

                <div class="col-xs-11 col-sm-8 col-md-8 col-lg-8 right_part">
                    <h2><?php echo $value['title']; ?></h2>
                    <?php echo $value['shortDesc']; ?>
                </div>
            </div>
        </li>

        <?php endforeach ?>

    </ul>
</div>
<?php echo $this->pagination($this->path); ?>






<!--
echo $this->form;

div#test>ul.some>li*5>lorem
-->