
<ul class="list">

    <?php foreach ($this->articles as $value): ?>
        <li id="contentWrapper<?php echo $value['id']; ?>">

            <div class="contentWrapper">

                <a class="superLink" href="/admin/article/edit/id/<?php echo $value['id']; ?>" name="<?php echo $value['id']; ?>"></a>

                <div class="contentLeftPart">

                    <img  src="/img/article/<?php echo $value['id']; ?>/<?php echo $value['miniImg']; ?>" class="miniImg"  alt="miniImg"/>

                    <div class="author">
                        <p><?php echo $value['updateDate']; ?></p>
                    </div>
                </div>

                <div class="contentRightPart">

                    <div class="contentText">
                        <h2><?php echo $value['title']; ?></h2>
                        <p><?php echo $value['shortDesc']; ?></p>
                    </div>

                    <!--<div class="rating">

                        <?php

                        $a = (int)$value['ratingGood'];
                        $b = (int)$value['ratingBad'];
                        $uniqueId = (int)$value['id'];

                        $c = $a + $b;

                        @$proc1 = ($a * 100) / $c;
                        @$proc2 = ($b *100) / $c;

                        $proc1R = round($proc1);
                        $proc2R = round($proc2);
                        $sumR = $proc1 + $proc2;

                        require('css/style.php');

                        ?>

                        <div class="left">
                            <div class="blade<?php echo $uniqueId; ?>">
                                <div class="topBlue<?php echo $uniqueId; ?>"></div>
                                <div class="middleBlue<?php echo $uniqueId; ?>"></div>
                            </div>
                            <div class="downBlue<?php echo $uniqueId; ?> "></div>
                        </div>
                        <div class="right">
                            <div class="blade<?php echo $uniqueId; ?>">
                                <div class="topRed<?php echo $uniqueId; ?>"></div>
                                <div class="middleRed<?php echo $uniqueId; ?>"></div>
                            </div>
                            <div class="downRed<?php echo $uniqueId; ?>"></div>
                        </div>
                    </div>-->

                </div>


                <div class="delete_cross">
                    <input class='artDeleteInput' type='image' src='/img/forceIcone/f_icon_pull1.png' value='<?php echo $value['id'] ?>' title='<?php echo $value['id'] ?>'>
                </div>

            </div>

        </li>
    <?php endforeach ?>
</ul>

<?php echo $this->pagination(); ?>






<!--
echo $this->form;

div#test>ul.some>li*5>lorem
-->