<?php

$identity = Zend_Auth::getInstance()->getStorage()->read();

foreach ($this->receive as $value):

?>



<div class="mediaWrap">
    <div class="episodeWrap">
        <div class="poster" title="<?php echo $value['title']; ?>">
            <img src="/img/movie/<?php echo $value['id']; ?>/miniImg/<?php echo $value['miniImg']; ?>" alt="<?php echo $value['title']; ?>"
            <a href="/admin/movie/view/id/<?php echo $value['id']; ?>"></a>
        </div>
    </div>
</div>

<?php endforeach; ?>

