<div class="container movie_wrap">

    <?php foreach ($this->movie as $value): ?>

    <div class="episode_wrap col-xs-12 col-sm-6 col-md-4 col-lg-4">
        <div class="col-xs-12 img-thumbnail">
            <div class="delete_cross">
                <input data-param="movie" class='delete_article' type='image' src='/img/style/remove_close_button_x_delete.png' value='<?php echo $value['id'] ?>' title='<?php echo $value['id'] ?>'>
            </div>

            <div class="episode_poster" title="<?php echo $value['title']; ?>">
                <a class="block_link" href="/admin/movie/edit/id/<?php echo $value['id']; ?>"></a>
                <img class="img-responsive" src="/img/movie/<?php echo $value['id']; ?>/<?php echo $value['miniImg']; ?>" alt="<?php echo $value['title']; ?>" />
            </div>
        </div>
    </div>

    <?php endforeach; ?>

</div>
